### ISSUE TITLE
Player Pointer Not found

### ISSUE THREAD

**Issue by ScottJurgenson** [bouletmarc/D2R-BMBot#29]
Running fullscreen at 1080p resolution. 

The game creates then the mouse clicks around a few times OR the esc key screen comes up. 

it sits there for maybe 30 seconds throws the below error then remakes and repeats. 

Leaving Player pointer not found!  (01:25:44)

**Comment by ScottJurgenson** [comment]
Bot started!  (01:24:00)
------------------------------------------  (01:24:00)
Extracting Infos...  (01:24:00)
D2R is running...  (01:24:00)
Screen Specs:  (01:24:00)
-> Screen size: 1920, 1080  (01:24:00)
-> D2R rect Size: 1920, 1080  (01:24:00)
-> D2R rect offset: 0, 0  (01:24:00)
-> D2R Center Position: 960, 540  (01:24:00)
D2R module BaseAddress: 0x7FF7183B0000  (01:24:00)
UnitTable offset: 0x22C6090  (01:24:00)
UI offset: 0x22D5D82  (01:24:01)
Expansion offset: 0x21E1D88  (01:24:01)
Game data offset: 0x29C7C38  (01:24:01)
Menu offset: 0x21E5248  (01:24:01)
Hover offset: 0x21E28A0  (01:24:01)
Roster offset: 0x22DC308  (01:24:01)
All games available offset: 0x2A19F10  (01:24:01)
Selected game offset: 0x29DBD10  (01:24:01)
Selected Char offset: 0x1E1EEF8  (01:24:01)
Starting loop timer!  (01:24:01)
------------------------------------------  (01:24:01)
Bot started for: Sorceress - crumbrum  (01:24:01)
Bot will stop!  (01:24:09)
Bot stopped!  (01:24:09)
Saved 'Sorceress.txt' file!  (01:24:34)
Saved 'CharSettings.txt' file!  (01:24:34)
Saved 'BotSettings.txt' file!  (01:24:46)
Saved 'BotSettings.txt' file!  (01:25:03)
Saved 'BotSettings.txt' file!  (01:25:05)
Bot will start!  (01:25:06)
Bot started!  (01:25:06)
------------------------------------------  (01:25:06)
Extracting Infos...  (01:25:06)
D2R is running...  (01:25:06)
Screen Specs:  (01:25:06)
-> Screen size: 1920, 1080  (01:25:06)
-> D2R rect Size: 1920, 1080  (01:25:06)
-> D2R rect offset: 0, 0  (01:25:06)
-> D2R Center Position: 960, 540  (01:25:06)
D2R module BaseAddress: 0x7FF7183B0000  (01:25:06)
UnitTable offset: 0x22C6090  (01:25:06)
UI offset: 0x22D5D82  (01:25:06)
Expansion offset: 0x21E1D88  (01:25:06)
Game data offset: 0x29C7C38  (01:25:06)
Menu offset: 0x21E5248  (01:25:06)
Hover offset: 0x21E28A0  (01:25:06)
Roster offset: 0x22DC308  (01:25:06)
All games available offset: 0x2A19F10  (01:25:06)
Selected game offset: 0x29DBD10  (01:25:06)
Selected Char offset: 0x1E1EEF8  (01:25:06)
Starting loop timer!  (01:25:06)
------------------------------------------  (01:25:06)
Bot started for: Sorceress - crumbrum  (01:25:06)
Changing Char...  (01:25:12)
Creating Game: lkscotts017  (01:25:16)
Changing Char...  (01:25:23)
Creating Game: lkscotts018  (01:25:25)
Leaving Player pointer not found!  (01:25:44)
Game Time: 00:41:211  (01:25:47)
Changing Char...  (01:25:53)
Creating Game: lkscotts019  (01:25:56)
Changing Char...  (01:26:03)
Creating Game: lkscotts019  (01:26:06)
Bot will stop!  (01:26:22)
Bot will start!  (01:27:56)
Bot started!  (01:27:56)
------------------------------------------  (01:27:56)
Extracting Infos...  (01:27:56)
D2R is running...  (01:27:56)
Screen Specs:  (01:27:56)
-> Screen size: 1920, 1080  (01:27:56)
-> D2R rect Size: 1920, 1080  (01:27:56)
-> D2R rect offset: 0, 0  (01:27:56)
-> D2R Center Position: 960, 540  (01:27:56)
D2R module BaseAddress: 0x7FF7183B0000  (01:27:56)
UnitTable offset: 0x22C6090  (01:27:56)
UI offset: 0x22D5D82  (01:27:57)
Expansion offset: 0x21E1D88  (01:27:57)
Game data offset: 0x29C7C38  (01:27:57)
Menu offset: 0x21E5248  (01:27:57)
Hover offset: 0x21E28A0  (01:27:57)
Roster offset: 0x22DC308  (01:27:57)
All games available offset: 0x2A19F10  (01:27:57)
Selected game offset: 0x29DBD10  (01:27:57)
Selected Char offset: 0x1E1EEF8  (01:27:57)
Starting loop timer!  (01:27:57)
------------------------------------------  (01:27:57)
Bot started for: Sorceress - crumbrum  (01:27:57)
Leaving Player pointer not found!  (01:28:01)

**Comment by ScottJurgenson** [comment]
Changing Char...  (01:20:58)
Changing Char...  (01:21:08)
Changing Char...  (01:21:18)
Leaving Player pointer not found!  (01:21:40)
Changing Char...  (01:21:49)
Changing Char...  (01:21:59)
Leaving Player pointer not found!  (01:22:21)
Changing Char...  (01:22:29)
Changing Char...  (01:22:40)
Changing Char...  (01:23:25)
Changing Char...  (01:23:34)
Changing Char...  (01:23:42)
Changing Char...  (01:25:12)
Changing Char...  (01:25:23)
Leaving Player pointer not found!  (01:25:44)
Changing Char...  (01:25:53)
Changing Char...  (01:26:03)
Leaving Player pointer not found!  (01:28:01)

**Comment by ScottJurgenson** [comment]
------------------------------------------  (01:20:51)
Screen Specs:  (01:20:51)
-> Screen size: 1920, 1080  (01:20:51)
-> D2R rect Size: 1920, 1080  (01:20:51)
-> D2R rect offset: 0, 0  (01:20:51)
-> D2R Center Position: 960, 540  (01:20:51)
------------------------------------------  (01:20:52)
Bot started for: Sorceress - crumbrum  (01:20:52)
Game Time: 00:00:628  (01:20:52)
Game Time: 00:51:372  (01:21:43)
Game Time: 01:32:7  (01:22:23)
------------------------------------------  (01:23:18)
Screen Specs:  (01:23:18)
-> Screen size: 1920, 1080  (01:23:18)
-> D2R rect Size: 1920, 1080  (01:23:18)
-> D2R rect offset: 0, 0  (01:23:18)
-> D2R Center Position: 960, 540  (01:23:18)
------------------------------------------  (01:23:19)
Bot started for: Sorceress - crumbrum  (01:23:19)
------------------------------------------  (01:24:00)
Screen Specs:  (01:24:00)
-> Screen size: 1920, 1080  (01:24:00)
-> D2R rect Size: 1920, 1080  (01:24:00)
-> D2R rect offset: 0, 0  (01:24:00)
-> D2R Center Position: 960, 540  (01:24:00)
------------------------------------------  (01:24:01)
Bot started for: Sorceress - crumbrum  (01:24:01)
------------------------------------------  (01:25:06)
Screen Specs:  (01:25:06)
-> Screen size: 1920, 1080  (01:25:06)
-> D2R rect Size: 1920, 1080  (01:25:06)
-> D2R rect offset: 0, 0  (01:25:06)
-> D2R Center Position: 960, 540  (01:25:06)
------------------------------------------  (01:25:06)
Bot started for: Sorceress - crumbrum  (01:25:06)
Game Time: 00:41:211  (01:25:47)
------------------------------------------  (01:27:56)
Screen Specs:  (01:27:56)
-> Screen size: 1920, 1080  (01:27:56)
-> D2R rect Size: 1920, 1080  (01:27:56)
-> D2R rect offset: 0, 0  (01:27:56)
-> D2R Center Position: 960, 540  (01:27:56)
------------------------------------------  (01:27:57)
Bot started for: Sorceress - crumbrum  (01:27:57)

**Comment by E1ila** [comment]
Sometimes when changing act through WP it manages to find the pointer.

I've noticed it tends to happen in act 1-4 and works well in 5.

**Comment by E1ila** [comment]
Found out this happens when there are multiple instances, the reason was (at least in my case) that the `process` var in Form1.cs was always using the 1st instance it found `process = Process.GetProcessesByName("D2R")[0];` instead of looking for the process of the hWnd it already had.

Fixed code -
```
                foreach (Process p in ProcList)
                {
                    if ((int)p.MainWindowHandle == hWnd)
                    {
                        process = p;
                        break;
                    }
                }
                if (process == null)
                {
                    process = ProcList[0];
                }
```
works every time now.

Of course you need to make sure hWnd contains the right handle, I gave different name for each window and configured the bot to search for the one I want to use.

**Comment by jkieffer0157** [comment]
For us non coders...where do i find this Form1.cs?

**Comment by jkieffer0157** [comment]
Figured out the form1cs and added the above code but still have the same issue.

D2R rect Size ratio is not 16:9!  (01:00:13)
Changing Char...  (01:00:19)
Changing Char...  (01:00:29)
Leaving Player pointer not found!  (01:00:46)
Changing Char...  (01:00:54)
Changing Char...  (01:01:05)
Leaving Player pointer not found!  (01:01:21)
Changing Char...  (01:01:30)
